/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iceCandyAssetProviderSol from "./IceCandyAssetProvider.sol";
export * as iceCandyAssetStoreSol from "./IceCandyAssetStore.sol";
