version: '3'
services:
  icecandy_localchain:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: icecandy_localchain
    ports:
      - 8545:8545
    volumes:
      - ./:/usr/src/app
    command: yarn hardhat node
