version: '3'
services:
  icecandy_localchain:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    container_name: icecandy_localchain
    ports:
      - 8545:8545
    volumes:
      - ./.env:/usr/src/app/.env
    command: /usr/src/app/node_modules/.bin/hardhat node
