/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { INFTCollectionModule } from "./INFTCollectionModule";
export type { IProfile } from "./IProfile";
