/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as assetstore from "./assetstore";
export type { assetstore };
import type * as core from "./core";
export type { core };
import type * as interface from "./interface";
export type { interface };
