/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as assetstore from "./assetstore";
export { IIceCandy__factory } from "./IIceCandy__factory";
export { INFTCollectionModule__factory } from "./INFTCollectionModule__factory";
export { IProfile__factory } from "./IProfile__factory";
