/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { INFTCollectionModule__factory } from "./INFTCollectionModule__factory";
export { IProfile__factory } from "./IProfile__factory";
