/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as bases from "./bases";
export type { bases };
import type * as modules from "./modules";
export type { modules };
export type { IceCandy } from "./IceCandy";
export type { Profile } from "./Profile";
