/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iceCandyAssetProviderSol from "./IceCandyAssetProvider.sol";
export type { iceCandyAssetProviderSol };
import type * as iceCandyAssetStoreSol from "./IceCandyAssetStore.sol";
export type { iceCandyAssetStoreSol };
